### ISSUE TITLE
Compress existing mzml file?

### ISSUE THREAD

**Issue by epoyraz** [PRIDE-Utilities/ms-data-core-api#14]
Hi,

i have a multiple .mzml files where the spectrum data is not compressed.
Is it possible to load the files with ms-data-core-api and save it with (e.g.) zlib compression ?

**Comment by ypriverol** [comment]
@epoyraz ms-data-core-api do not provide functionalities to write the files, if you want to write you must use the original API's for example mzML can be handle using jmzML. If you want to provide this functionalities, then you will need to extend the current implementation of ms-data-core-api. 

The only export functionality from the current model was provided for identifications to mztab files.

**Comment by epoyraz** [comment]
I see.
Thanks.
I'll look into that.
