### ISSUE TITLE
Parsing of some assays seems to hang

### ISSUE THREAD

**Issue by KennethVerheggen** [PRIDE-Utilities/ms-data-core-api#16]
Hello,

I discovered that some projects cause the parsing to hang indefinitely. This seems the case on my end for example for assay 42095.

Cheers,

Kenneth

**Comment by ypriverol** [comment]
@KennethVerheggen can you take a look in details to that. If you have any doubts about how to work with ms-data-core-api we can help you.  If you can't we can take the issue.

**Comment by Tobias-Ternent** [comment]
@KennethVerheggen is this still a problem for you? I recently have been looking into improving the performance of ms-data-core-api for processing over mzIdentML files. I have made a new snapshot deployment for further testing about this, version: 2.0.10-SNAPSHOT
Please could you give that at try? I have tested using the assay you mentioned - the mzid file and its peak file, using a validator command-line tool I made: https://github.com/PRIDE-Toolsuite/PGConverter
I managed to iterate through all the proteins and peptides in about 90 minutes, and given as much RAM as it wanted, used a maximum of 30 GB of RAM.

Here's a summary of a 'validation report' that I produced from this assay:
Name: /nfs/pride/drop/pride-drop-006/tternent_test/mzid_complex_cache_clear_test/iTRAQ86_20120928b.mzid
Shortlabel: 
Contacts: 
Instruments: 
Software: 
SearchDatabase: SP12_5_HomoSapiens_20120910.fasta
ExampleProteinAccession: Q9BZL6
ProteinGroupPresent: true
Assay Group CvParams: {[PRIDE,Date of search,PRIDE:0000219,Thu Nov 13 10:05:20 GMT 2014],[PSI-MS,Mascot MGF file,MS:1001062,null],[PSI-MS,multiple peak list nativeID format,MS:1000774,null]}
Assay Group UserParams: {}
Chromatogram: false
Total proteins: 5622
Total peptides: 437729
Total unique peptides: 21345
Total spectra: 340095
Total identified spectra: 340095
Total missing spectra: 0
Total unique PTMs: [UNIMOD,Carbamidomethyl,UNIMOD:4,null],[UNIMOD,Oxidation,UNIMOD:35,null]
Delta m/z: 0%
Match fragment ions: true
