### ISSUE TITLE
Failing CI build on Travis

### ISSUE THREAD

**Issue by khmarbaise** [PRIDE-Utilities/ms-data-core-api#20]
Currently the http://www.ebi.ac.uk/intact/maven/nexus/content/repositories/ebi-repo/uk/ac/ebi/pride/jmztab-modular-model/3.0.2/jmztab-modular-model-3.0.2.jar produces a failure...

**Comment by ypriverol** [comment]
thanks @khmarbaise we will fix the error, we have been moving to a new maven platform. Thanks for reporting the error.

**Comment by ypriverol** [comment]
Issue solve. Thanks for reporting it. We just deployed the new version of jmztab 3.03.
