### ISSUE TITLE
Standardising the the modifications to UNIMOD 

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Utilities/ms-data-core-api#38]
We need to standardize the modifications from all the submissions using the pride-mod library. If one modification is not found then we should be thrown an exception. 

**All the modifications will be finally represented as UNIMOD Terms.** 

Related with this issue: https://github.com/PRIDE-Utilities/ms-data-core-api/issues/35

**Comment by sureshhewabi** [comment]
Completed
